### PR TITLE
Added all the versions of minecraft 

### PR DESCRIPTION
**Pull request by hube12**
The script for future reference
```python
import json
import urllib.request
from urllib.error import HTTPError, URLError
def download_file(url, filename):
    try:
        print(f'Downloading {filename}...')
        f = urllib.request.urlopen(url)
        with open(filename, 'wb+') as local_file:
            local_file.write(f.read())
    except HTTPError as e:
        print('HTTP Error')
        print(e)
    except URLError as e:
        print('URL Error')
        print(e)

download_file("https://launchermeta.mojang.com/mc/game/version_manifest.json", f"version_manifest.json")

with open("version_manifest.json") as file:
    versions=json.load(file)["versions"]
    versions.reverse()
    typf=lambda typ:"SNAPSHOT" if typ=="snapshot" else "RELEASE" if typ=="release" else "OLD_ALPHA" if typ=="old_alpha" else "OLD_BETA" if typ=="old_beta" else "NONE"
    for i,version in enumerate(versions):
        print("const Version","MC_"+version.get("id").replace(".","_").replace("-","_").replace(" ","_"),"= {",
              i,",",typf(version.get("type")),",",'"'+version.get("releaseTime")+'"',"};")
```

### CODE REVIEW

**Comment by Earthcomputer** [comment]
Is it not possible to download the version_manifest.json at runtime in the C++? This file is going to be a maintenance burden.

**Comment by hube12** [comment]
Oh right i can make it with cmake, let me do that

**Comment by hube12** [comment]
Ok now it will generate directly when you run cmake

**Comment by Earthcomputer** [comment]
Just curious, how would you use this as a library now? We're going to have to publish a package somewhere.

**Comment by hube12** [comment]
i would submodule it or use conan.io

**Pull request merged**
